const audioMap: Record<string, string> = {
  "Чёрный бумер|Серёга": "/audio/media1.mp3",
  "В клубе|Тимати": "/audio/media3.mp3",
  "Казанова|Валерий Леонтьев": "/audio/media5.mp3",
  "Candy Shop|50 Cent Feat. Olivia": "/audio/media7.mp3",
  "Зацепила|Артур Пирожков": "/audio/media9.mp3",
  "Not Like Us|Kendrick Lamar": "/audio/media11.mp3",
  "Felicita|Al Bano & Romina Power": "/audio/media13.mp3",
  "Be My Lover|La Bouche": "/audio/media15.mp3",
  "Leave The Door Open|Bruno Mars": "/audio/media17.mp3",
  "Don't Stop The Music|Rihanna": "/audio/media19.mp3",
  "Сияй|Ramil'": "/audio/media21.mp3",
  "Чёрный кот|Тамара Миансарова": "/audio/media23.mp3",
  "Горький Вкус|Султан Лагучев": "/audio/media25.mp3",
  "Voyage, voyage|Desireless": "/audio/media27.mp3",
  "Op|Tarkan": "/audio/media29.mp3",
  "Пачка Сигарет|Кино": "/audio/media31.mp3",
  "Bamboleo|Gipsy Kings": "/audio/media33.mp3",
  "Lay All Your Love On Me|Abba": "/audio/media35.mp3",
  "Kissing Strangers|DNCE feat. Nicki Minaj": "/audio/media37.mp3",
  "Cake By The Ocean|DNCE": "/audio/media39.mp3",
  "Лишь До Утра|Dan Balan": "/audio/media41.mp3",
  "Фаина|На-На": "/audio/media43.mp3",
  "Это всё она|Сергей Лазарев": "/audio/media45.mp3",
  "Freed from desire|GALA": "/audio/media47.mp3",
  "Life Is Life|Opus": "/audio/media49.mp3",
  "That That|Psy (prod. & feat. SUGA of BTS)": "/audio/media51.mp3",
  "Шоколадный заяц|Пьер Нарцисс": "/audio/media53.mp3",
  "Зеленоглазое такси|Михаил Боярский": "/audio/media55.mp3",
  "Waving Flag|K'naan": "/audio/media57.mp3",
  "Beautiful Life|Ace Of Base": "/audio/media59.mp3",
  "Criminal|Britney Spears": "/audio/media61.mp3",
  "Susanna|Adriano Celentano": "/audio/media63.mp3",
  "Между нами любовь|SEREBRO": "/audio/media65.mp3",
  "Step Up|Darin": "/audio/media67.mp3",
  "Mr. Saxobeat|Alexandra Stan": "/audio/media69.mp3",
  "Жить в кайф|Макс Корж": "/audio/media71.mp3",
  "Je veux|ZAZ": "/audio/media72.mp3",
  "Ла ла ла|Жанна Фриске": "/audio/media73.mp3",
  "Zitti E Buoni|Maneskin": "/audio/media74.mp3",
  "Поезда|Женя Трофимов": "/audio/media75.mp3",
  "Люби меня|Отпетые мошенники": "/audio/media76.mp3",
  "По барам|Анна ASTI": "/audio/media77.mp3",
  "Попутчица|Слава": "/audio/media78.mp3",
  "С Днем Рождения|Ирина Аллегрова": "/audio/media79.mp3",
  "Остров|Леонид Агутин": "/audio/media80.mp3",
  "Numb + Башня|Linkin Park / Даня Милохин & Мумий Тролль": "/audio/media81.mp3",
  "Rolling in the Deep + На Титанике|Adele / Лолита": "/audio/media83.mp3",
  "Что такое осень + Riptide|ДДТ / Vance Joy": "/audio/media85.mp3",
  "I Was Made For Lovin' You + Прыгну со скалы|KISS / Король и Шут": "/audio/media87.mp3",
  "Camry 3.5 + Starboy|UncleFlexxx / The Weeknd ft. Daft Punk": "/audio/media89.mp3",
  "АУ|Ляпис Трубецкой": "/audio/media91.mp3",
  "Никаких Больше Вечеринок|Cream Soda": "/audio/media93.mp3",
  "Ах, какая женщина|Фристайл": "/audio/media95.mp3",
  "Ориентация Север|Лолита": "/audio/media97.mp3",
  "Radioactive|Imagine Dragons": "/audio/media99.mp3",
  "La la la|Naughty Boy ft. Sam Smith": "/audio/media101.mp3",
  "Все будет хорошо|Митя Фомин": "/audio/media103.mp3",
  "Щека на щеку|Шарлот": "/audio/media105.mp3",
  "Appelle mon numéro|Mylène Farmer": "/audio/media107.mp3",
  "ЛА ЛА ЛА|Клава Кока": "/audio/media109.mp3",
  "Señorita|Shawn Mendes, Camila Cabello": "/audio/media111.mp3",
  "Косил Ясь конюшину|Песняры": "/audio/media113.mp3",
  "Hafanana|Afric Simone": "/audio/media115.mp3",
  "All Around The World (La La La)|ATC": "/audio/media117.mp3",
  "Lalala|Y2K, bbno$": "/audio/media119.mp3",
  "Золото|Супер Жорик": "/audio/media121.mp3",
  "Everybody (Backstreet's Back)|Backstreet Boys": "/audio/media123.mp3",
  "Shots|LMFAO ft. Lil Jon": "/audio/media125.mp3",
  "Rock This Party|Bob Sinclar": "/audio/media127.mp3",
  "Party for Everybody|Бурановские бабушки": "/audio/media129.mp3",
  "The Fox (What Does the Fox Say?)|Ylvis": "/audio/media131.mp3",
  "Papaoutai|Stromae": "/audio/media133.mp3",
  "I'm Sexy and I Know It|LMFAO": "/audio/media135.mp3",
  "Call Me Maybe|Carly Rae Jepsen": "/audio/media137.mp3",
  "Coco Jamboo|Mr. President (9Tendo)": "/audio/media139.mp3",
}

export function getAudioUrl(song: string, artist: string): string | null {
  return audioMap[`${song}|${artist}`] ?? null
}
